- name: init k8s master and node
  become: yes 
  become_user: root
  become_method: sudo
  hosts: all
  roles: 
    - infra
    - vim
    - python3
    - docker
    - role: swap
      tags: swap
    - k8s