---
# tasks file for k8s
- name: Ensure dependencies are installed.
  apt:
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - curl

- name: use the aliyun mirror fingerprint
  apt_key:
    url: "{{ k8s_apt_gpg_key_url }}"
    id: "{{ k8s_apt_gpg_fingerprint }}"


- name: remove the existed k8s repo
  file:
    path: /etc/apt/sources.list.d/k8s.list
    state: absent

- name: Add Aliyun k8s repository.
  copy:
    content: |
      {{k8s_apt_repo}}
    dest: /etc/apt/sources.list.d/k8s.list
    force: yes
    backup: yes
    group: root
    owner : root

- name: update apt source index
  apt:
    update_cache: yes


- name: Install Kubernetes binaries
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet 
      - kubeadm 
      - kubectl

# - name: Configure node ip
#   lineinfile:
#     path: /etc/default/kubelet
#     line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

# todo: setup the host file with node_ip and hostname
# todo: k8s brige
#  [root@node-1 ~]# cat <<EOF >  /etc/sysctl.d/k8s.conf
# > net.bridge.bridge-nf-call-ip6tables = 1
# > net.bridge.bridge-nf-call-iptables = 1
# > EOF
# sysctl --system to update
- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
# beforehand using 'kubeadm config images pull'"
# temply manual
# vim /etc/kubernetes/kubelet 将下项修改
# KUBELET_POD_INFRA_CONTAINER="--pod-infra-container-image=index.tenxcloud.com/google_containers/pause:3.0"

# vim  /etc/docker/daemon.json
# {
#   "registry-mirrors": ["http://f1361db2.m.daocloud.io"]
# }
# https://www.daocloud.io/mirror#accelerator-doc

# download the k8s image, please manually download.
# refer to the ./files/k8s_image.yml


# only for master
- name: Initialize the Kubernetes cluster using kubeadm
  command: > 
    kubeadm init \
      --apiserver-advertise-address="192.168.3.73" \
      --apiserver-cert-extra-sans="192.168.3.73"  \
      --node-name pi4.local \
      --pod-network-cidr=192.168.0.0/16
  register: k8s_initialzation_result

- name: output the initiazation ruesult
  debug: var=k8s_initialzation_result
