---
# tasks file for infra
- name: replace apt-source to aliyun mirror
  copy:
    content: |
      deb https://mirrors.aliyun.com/raspbian/raspbian/ buster main non-free contrib
      deb-src https://mirrors.aliyun.com/raspbian/raspbian/ buster main non-free contrib
    dest: /etc/apt/sources.list
    force: yes
    backup: yes
    group: root
    owner : root

- name: update apt source index
  apt:
    update_cache: yes

- name: Add the br_netfilter for k8s bridge
  modprobe:
    name: br_netfilter
    state: present

# i don not know why:https://github.com/kubernetes/kubeadm/issues/312
- name: setup the bridge wit iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
